namespace:
  name: 'app'

metadata:
  name: 'entry'

labels:
  env: 'dev'
  cluster: 'luxrobo'

image:
  tag: latest
  repository: 012634413971.dkr.ecr.ap-northeast-2.amazonaws.com/entry
  imagePullPolicy: Always
  imagePullSecrets: ap-northeast-2-ecr-registry

service:
  http: 80
  targetHttp: 3000

ingress:
  host: dev-entry
  domain: luxrobo.com
  targetHttp: 80
